version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
        name: check-updated-files
          feature/.* run-feature-job true
          ui/.* run-ui-job true
        base-revision: main
        config-path: .circleci/continue_config.yml
